# Generated by Django 4.2.2 on 2023-08-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("IdTicket", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Sede",
                    models.IntegerField(
                        choices=[
                            (0, "Casa Central"),
                            (1, "Hospital del trabajador [HT]"),
                            (2, "Centro Medico [CEM]"),
                            (3, "ESACHS [Ramon Carnicer 151]"),
                            (4, "Rancagua 333"),
                            (5, "OTEC"),
                            (6, "ESE-CENTRO DE COMANDO [TERRENO]"),
                        ],
                        null=True,
                    ),
                ),
                ("Direccion", models.CharField(max_length=200)),
                ("Area", models.CharField(max_length=200)),
                (
                    "Modalidad",
                    models.IntegerField(
                        choices=[(0, "PRESENCIAL"), (1, "TELETRABAJO")], null=True
                    ),
                ),
                ("Nombre", models.CharField(max_length=200)),
                ("Rut", models.CharField(max_length=12)),
                ("Usuario", models.CharField(max_length=200)),
                ("CorreoInstitucional", models.EmailField(max_length=254)),
                ("Telefono", models.CharField(max_length=12)),
                ("FechaEmision", models.DateTimeField(auto_now_add=True)),
                (
                    "TipoReporte",
                    models.IntegerField(
                        choices=[(0, "INCIDENCIA"), (1, "REQUERIMIENTO")], null=True
                    ),
                ),
                ("Solicitud", models.CharField(default="", max_length=600)),
            ],
        ),
    ]
