# Generated by Django 4.2.2 on 2023-08-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_imagen_alter_ticket_modalidad_alter_ticket_sede_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="HOSTNAME",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="IP",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="MARCA_MODELO",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
